services:

  cfgsync:
    container_name: cfgsync
    build:
      context: .
      dockerfile: tools/Dockerfile
    image: logos-blockchain:latest
    volumes:
      - ./tools:/etc/logos-blockchain
    entrypoint: /etc/logos-blockchain/scripts/run_cfgsync_server.sh

  logos-blockchain-node:
    build:
      context: .
      dockerfile: tools/Dockerfile
    volumes:
      - ./tools:/etc/logos-blockchain
    deploy:
      replicas: ${DOCKER_COMPOSE_LIBP2P_REPLICAS:-1}
    depends_on:
      - cfgsync
    entrypoint: /etc/logos-blockchain/scripts/run_logos_blockchain_node.sh
