network:
  backend:
    swarm:
      host: 0.0.0.0
      port: 52115
      node_key: 572a7e1efdbe597e00e6f73aca499387a18946fc495db44790e85bb236019829
      gossipsub_config:
        history_length: 5
        history_gossip: 3
        mesh_n: 6
        mesh_n_low: 5
        mesh_n_high: 12
        retain_scores: 4
        gossip_lazy: 6
        gossip_factor: 0.25
        heartbeat_initial_delay:
          secs: 5
          nanos: 0
        heartbeat_interval:
          secs: 1
          nanos: 0
        fanout_ttl:
          secs: 60
          nanos: 0
        check_explicit_peers_ticks: 300
        duplicate_cache_time:
          secs: 60
          nanos: 0
        validate_messages: false
        allow_self_origin: false
        do_px: false
        prune_peers: 0
        prune_backoff:
          secs: 60
          nanos: 0
        unsubscribe_backoff:
          secs: 10
          nanos: 0
        backoff_slack: 1
        flood_publish: true
        graft_flood_threshold:
          secs: 10
          nanos: 0
        mesh_outbound_min: 2
        opportunistic_graft_ticks: 60
        opportunistic_graft_peers: 2
        gossip_retransimission: 3
        max_messages_per_rpc: null
        max_ihave_length: 5000
        max_ihave_messages: 10
        iwant_followup_time:
          secs: 3
          nanos: 0
        published_message_ids_cache_time:
          secs: 10
          nanos: 0
      kademlia_config:
        client_mode: false
      identify_config: {}
      chain_sync_config:
        peer_response_timeout: 60000
      nat_config:
        type: traversal
        autonat:
          retest_successful_external_addresses_interval:
            secs: 0
            nanos: 0
        mapping:
          timeout: '1.000000000'
          lease_duration:
            secs: 7200
            nanos: 0
          max_retries: 3
          renewal_delay_fraction: 0.8
          retry_interval:
            secs: 30
            nanos: 0
        gateway_monitor:
          check_interval:
            secs: 300
            nanos: 0
    initial_peers: []
blend:
  non_ephemeral_signing_key_id: ac3035da5acbe088ec70638ebd319e1cb46d43c1cf4bb38c1f1bd4d308dc8c19
  recovery_path_prefix: ./recovery/blend
  core:
    backend:
      listening_address: /ip4/127.0.0.1/udp/59100/quic-v1
      core_peering_degree:
        start: 1
        end: 3
      edge_node_connection_timeout:
        secs: 1
        nanos: 0
      max_edge_node_incoming_connections: 300
      max_dial_attempts_per_peer: 3
    zk:
      secret_key_kms_id: 935e1eedba05726610f6cadccd2020a486ca10acbdfc9926dc62e0a11f57d720
  edge:
    backend:
      max_dial_attempts_per_peer_per_message: 1
      replication_factor: 1
cryptarchia:
  service:
    starting_state: !Genesis
      genesis_tx:
        mantle_tx:
          ops:
          - opcode: 0
            payload:
              channel_id: '0000000000000000000000000000000000000000000000000000000000000000'
              inscription:
              - 103
              - 101
              - 110
              - 101
              - 115
              - 105
              - 115
              parent: '0000000000000000000000000000000000000000000000000000000000000000'
              signer: '0000000000000000000000000000000000000000000000000000000000000000'
          - opcode: 32
            payload:
              service_type: BN
              locators:
              - /ip4/127.0.0.1/udp/59100/quic-v1
              provider_id: ac3035da5acbe088ec70638ebd319e1cb46d43c1cf4bb38c1f1bd4d308dc8c19
              zk_id: 935e1eedba05726610f6cadccd2020a486ca10acbdfc9926dc62e0a11f57d720
              locked_note_id: 5f8735e66ff952d51a4467a7c5b76ddabd8180460dd5642182afaeedd0bb6a0f
          ledger_tx:
            inputs: []
            outputs:
            - value: 1000
              pk: 4f9df4dc37641175717823d8e1e3041978bff79766a45817dc8c28231655ac1c
            - value: 1
              pk: 510c37413d22516eb0c2ffac3a07612eeecaf8735147dec946043abaa5c14d0f
            - value: 100000
              pk: 18c44acbe9ec0ab66e83461c862351696a9cfbf25b546d4b86582dc190cdf50e
          execution_gas_price: 0
          storage_gas_price: 0
        ops_proofs:
        - NoProof
        - !ZkAndEd25519Sigs
          zk_sig:
            pi_a:
            - 177
            - 47
            - 8
            - 193
            - 28
            - 242
            - 111
            - 160
            - 37
            - 67
            - 91
            - 213
            - 231
            - 245
            - 80
            - 94
            - 206
            - 80
            - 2
            - 188
            - 211
            - 202
            - 86
            - 32
            - 253
            - 212
            - 72
            - 174
            - 235
            - 121
            - 212
            - 44
            pi_b:
            - 125
            - 103
            - 16
            - 21
            - 250
            - 18
            - 22
            - 76
            - 60
            - 140
            - 50
            - 60
            - 98
            - 214
            - 58
            - 207
            - 176
            - 155
            - 112
            - 139
            - 146
            - 224
            - 71
            - 177
            - 32
            - 84
            - 113
            - 210
            - 101
            - 15
            - 192
            - 16
            - 42
            - 18
            - 185
            - 191
            - 188
            - 53
            - 217
            - 247
            - 204
            - 88
            - 112
            - 67
            - 133
            - 221
            - 57
            - 123
            - 61
            - 177
            - 210
            - 213
            - 63
            - 207
            - 251
            - 38
            - 220
            - 185
            - 188
            - 173
            - 235
            - 185
            - 42
            - 29
            pi_c:
            - 70
            - 62
            - 65
            - 90
            - 168
            - 27
            - 170
            - 119
            - 159
            - 211
            - 41
            - 175
            - 138
            - 19
            - 10
            - 206
            - 150
            - 87
            - 233
            - 0
            - 104
            - 219
            - 32
            - 161
            - 126
            - 196
            - 68
            - 250
            - 252
            - 79
            - 36
            - 171
          ed25519_sig:
          - 48
          - 91
          - 62
          - 32
          - 249
          - 10
          - 187
          - 170
          - 95
          - 17
          - 117
          - 51
          - 129
          - 48
          - 78
          - 201
          - 12
          - 80
          - 149
          - 66
          - 195
          - 79
          - 151
          - 20
          - 217
          - 235
          - 125
          - 219
          - 235
          - 121
          - 249
          - 196
          - 19
          - 67
          - 130
          - 169
          - 164
          - 178
          - 85
          - 141
          - 21
          - 34
          - 84
          - 127
          - 157
          - 165
          - 124
          - 58
          - 211
          - 31
          - 226
          - 220
          - 77
          - 156
          - 145
          - 234
          - 153
          - 47
          - 136
          - 146
          - 81
          - 69
          - 101
          - 10
        ledger_tx_proof:
          pi_a:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          pi_b:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          pi_c:
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
          - 0
    recovery_file: ./recovery/cryptarchia.json
    bootstrap:
      prolonged_bootstrap_period: '1.000000000'
      force_bootstrap: false
      offline_grace_period:
        grace_period: '1200.000000000'
        state_recording_interval: '60.000000000'
  network:
    bootstrap:
      ibd:
        peers: []
        delay_before_new_download:
          secs: 10
          nanos: 0
    sync:
      orphan:
        max_orphan_cache_size: 5
  leader:
    pk: 4f9df4dc37641175717823d8e1e3041978bff79766a45817dc8c28231655ac1c
    sk: 6c64572a7e1efdbe597e00e6f73aca4900000000000000000000000000000000
time:
  backend:
    ntp_server: pool.ntp.org
    ntp_client_settings:
      timeout: '5.000000000'
      listening_interface: 0.0.0.0
    update_interval: '16.000000000'
  chain_start_time: 2026-01-29 13:43:30.583792 +00:00:00
mempool:
  recovery_path: ./recovery/mempool.json
tracing:
  logger: Stdout
  tracing: None
  filter: None
  metrics: None
  console: None
  level: DEBUG
sdp:
  declaration: null
  wallet_config:
    max_tx_fee: 18446744073709551615
    funding_pk: 18c44acbe9ec0ab66e83461c862351696a9cfbf25b546d4b86582dc190cdf50e
http:
  backend_settings:
    address: 127.0.0.1:8080
    cors_origins: []
    timeout:
      secs: 30
      nanos: 0
    max_body_size: 10485760
    max_concurrent_requests: 1000
    rate_limit_per_second: 10000
    rate_limit_burst: 10000
storage:
  db_path: ./db
  read_only: false
  column_family: blocks
key_management:
  keys:
    935e1eedba05726610f6cadccd2020a486ca10acbdfc9926dc62e0a11f57d720: !Zk ac3035da5acbe088ec70638ebd319e1cb46d43c1cf4bb38c1f1bd4d308dc8c19
    ac3035da5acbe088ec70638ebd319e1cb46d43c1cf4bb38c1f1bd4d308dc8c19: !Ed25519 572a7e1efdbe597e00e6f73aca499387a18946fc495db44790e85bb236019829
    18c44acbe9ec0ab66e83461c862351696a9cfbf25b546d4b86582dc190cdf50e: !Zk 736470572a7e1efdbe597e00e6f73aca00000000000000000000000000000000
wallet:
  known_keys:
  - 4f9df4dc37641175717823d8e1e3041978bff79766a45817dc8c28231655ac1c
  - 18c44acbe9ec0ab66e83461c862351696a9cfbf25b546d4b86582dc190cdf50e
testing_http:
  backend_settings:
    address: 127.0.0.1:50897
    cors_origins: []
    timeout:
      secs: 30
      nanos: 0
    max_body_size: 10485760
    max_concurrent_requests: 1000
    rate_limit_per_second: 10000
    rate_limit_burst: 10000
